version: '3'

services:
  discord-bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_PORT=${WEB_PORT}
      - HOST=${HOST}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.discord-bot_https.redirectScheme.scheme = https
      - traefik.http.routers.discord-bot.entrypoints = web
      - traefik.http.routers.discord-bot.middlewares = discord-bot_https@docker
      - traefik.http.routers.discord-bot.rule = Host(`${HOST}`)
      - traefik.http.routers.discord-bot_https.entrypoints = websecure
      - traefik.http.routers.discord-bot_https.rule = Host(`${HOST}`)
      - traefik.http.routers.discord-bot_https.tls = true
      - traefik.http.routers.discord-bot.tls=true
      - traefik.http.routers.discord-bot.tls.certresolver=letsencrypt
      - traefik.http.services.discord-bot.loadbalancer.server.port=${WEB_PORT}
    networks:
      - traefik-net

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/traefik.yml
      - --providers.docker.exposedbydefault=false
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge