version: '3'

services:
  discord-bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_PORT=${WEB_PORT}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - HOST=${HOST}
      - EMAIL=${EMAIL}
    volumes:
      - ./downloads:/app/downloads
    labels:
      - traefik.enable = true 
      - traefik.http.middlewares.discord-bot_https.redirectscheme.scheme = https
      - traefik.http.routers.discord-bot.entrypoints = web
      - traefik.http.routers.discord-bot.middlewares = discord-bot_https@docker
      - traefik.http.routers.discord-bot.rule = Host(`${HOST}`)
      - traefik.http.routers.discord-bot_https.entrypoints = websecure
      - traefik.http.routers.discord-bot_https.rule = Host(`${HOST}`)
      - traefik.http.routers.discord-bot_https.tls = true
      - traefik.http.services.portainer.loadbalancer.server.port=${WEB_PORT}
    networks:
      - traefik_default

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --accesslog=true
      - --metrics.prometheus=true
      - --entrypoints.metrics.address=:8081
      - --metrics.prometheus.entrypoint=metrics
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_default