services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads  # Для сохранения временных файлов