version: '3'

services:
  discord-bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_PORT=${WEB_PORT}
      - HOST=${HOST}
    labels:
      - traefik.enable=true
      # HTTP -> HTTPS redirect
      - traefik.http.routers.discord-bot-http.entrypoints=web
      - traefik.http.routers.discord-bot-http.rule=Host(`${HOST}`)
      - traefik.http.routers.discord-bot-http.middlewares=redirect-to-https@file
      # HTTPS router
      - traefik.http.routers.discord-bot.entrypoints=websecure
      - traefik.http.routers.discord-bot.rule=Host(`${HOST}`)
      - traefik.http.routers.discord-bot.tls=true
      - traefik.http.routers.discord-bot.tls.certresolver=letsencrypt
      - traefik.http.services.discord-bot.loadbalancer.server.port=${WEB_PORT}
    networks:
      - traefik-net

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
    ports:
      - "8080:8080"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge