version: '3'

services:
  discord-bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_PORT=${WEB_PORT}
      - HOST=${HOST}
    labels:
      - traefik.enable=true
      - traefik.http.routers.discord-bot-http.entrypoints=web
      - traefik.http.routers.discord-bot-http.rule=Host(`${HOST}`)
      - traefik.http.routers.discord-bot-http.middlewares=redirect-to-https@file
      - traefik.http.routers.discord-bot.entrypoints=websecure
      - traefik.http.routers.discord-bot.rule=Host(`${HOST}`)
      - traefik.http.routers.discord-bot.tls=true
      - traefik.http.routers.discord-bot.tls.certresolver=letsencrypt
      - traefik.http.services.discord-bot.loadbalancer.server.port=${WEB_PORT}
    networks:
      - traefik_default

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_default

networks:
  traefik_default:
    driver: bridge