name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.1
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test Connection
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Success!'"

      - name: Copy files via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/smusic-bot

      - name: Deploy with docker-compose
        env:
            IMAGE_REF: ${{ steps.meta.outputs.tags }}
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            WEB_PORT: ${{ secrets.WEB_PORT }}
            AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
            AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
            EMAIL: ${{ secrets.EMAIL }}
            HOST: ${{ secrets.HOST }}
        run: |
            echo IMAGE_REF:$IMAGE_REF
            echo EMAIL:$EMAIL
            echo HOST:$HOST
            ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /opt/smusic-bot && \
            docker-compose down && \
            docker-compose pull && \
            docker-compose up -d && \
            docker system prune -af"
